sed -i 's/AAA007-N19/Gen1/' phylogenomic_tree.tree
sed -i 's/AAA288-D22/Gen2/' phylogenomic_tree.tree
sed -i 's/AAA799-D07/Gen3/' phylogenomic_tree.tree
sed -i 's/AAA799-O18/Gen4/' phylogenomic_tree.tree
sed -i 's/Acidianus_hospitalis_W1/Gen5/' phylogenomic_tree.tree
sed -i 's/Aciduliprofundum_boonei_T469/Gen6/' phylogenomic_tree.tree
sed -i 's/Aigarchaeota_archaeon_JGI_0000106_J15/Gen7/' phylogenomic_tree.tree
sed -i 's/Aigarchaeota_archaeon_JGI_MDM2_JNZ_1_K18/Gen8/' phylogenomic_tree.tree
sed -i 's/Aigarchaeota_archaeon_NZ13_MG1/Gen9/' phylogenomic_tree.tree
sed -i 's/Aigarchaeota_archaeon_strain_OS1/Gen10/' phylogenomic_tree.tree
sed -i 's/Archaeoglobus_veneficus_SNP6/Gen11/' phylogenomic_tree.tree
sed -i 's/Caldivirga_maquilingensis_IC_167/Gen12/' phylogenomic_tree.tree
sed -i 's/Candidatus_Caldiarchaeum_subterraneum/Gen13/' phylogenomic_tree.tree
sed -i 's/Candidatus_Korarchaeum_cryptofilum_OPF8/Gen14/' phylogenomic_tree.tree
sed -i 's/Candidatus_Nitrosoarchaeum_koreensis_MY1/Gen15/' phylogenomic_tree.tree
sed -i 's/Candidatus_Nitrosocaldus_cavascurensis_strain/Gen146/' phylogenomic_tree.tree
sed -i 's/Candidatus_Nitrosocaldus_islandicus_isolate_3F/Gen17/' phylogenomic_tree.tree
sed -i 's/Candidatus_Nitrosocosmicus_franklandus_C13/Gen18/' phylogenomic_tree.tree
sed -i 's/Candidatus_Nitrosocosmicus_oleophilus_strain/Gen19/' phylogenomic_tree.tree
sed -i 's/Nitrosopelagicus_brevis_U25/Gen20/' phylogenomic_tree.tree
sed -i 's/Candidatus_Nitrosopelagicus_brevis_strain/Gen21/' phylogenomic_tree.tree
sed -i 's/Candidatus_Nitrosopelagicus_sp_Isolate_GoM/Gen22/' phylogenomic_tree.tree
sed -i 's/Candidatus_Nitrosopumilus_salaria_BD31/Gen23/' phylogenomic_tree.tree
sed -i 's/Candidatus_Nitrosopumilus_sp_MTA1/Gen24/' phylogenomic_tree.tree
sed -i 's/Candidatus_Nitrososphaera_evergladensis_SR1/Gen25/' phylogenomic_tree.tree
sed -i 's/Cenarchaeum_symbiosum_A/Gen26/' phylogenomic_tree.tree
sed -i 's/EGM_Bin1/Gen27/' phylogenomic_tree.tree
sed -i 's/EGM_Bin2/Gen28/' phylogenomic_tree.tree
sed -i 's/Ferroplasma_acidarmanus_fer1/Gen30/' phylogenomic_tree.tree
sed -i 's/HM45_Bin1/Gen31/' phylogenomic_tree.tree
sed -i 's/HM45_Bin2/Gen32/' phylogenomic_tree.tree
sed -i 's/HM58_Bin/Gen33/' phylogenomic_tree.tree
sed -i 's/HM79_Bin/Gen34/' phylogenomic_tree.tree
sed -i 's/HM81_Bin1/Gen35/' phylogenomic_tree.tree
sed -i 's/HM81_Bin2/Gen36/' phylogenomic_tree.tree
sed -i 's/HM82_Bin1/Gen37/' phylogenomic_tree.tree
sed -i 's/HM82_Bin2/Gen38/' phylogenomic_tree.tree
sed -i 's/Haladaptatus_paucihalophilus_DX253/Gen39/' phylogenomic_tree.tree
sed -i 's/Halogeometricum_borinquense_DSM_11551/Gen40/' phylogenomic_tree.tree
sed -i 's/Halorhabdus_utahensis_DSM_12940/Gen41/' phylogenomic_tree.tree
sed -i 's/Halorubrum_lacusprofundi_ATCC_49239/Gen42/' phylogenomic_tree.tree
sed -i 's/Marine_Group_1_crenarchaeote_sp_SCGC/Gen43/' phylogenomic_tree.tree
sed -i 's/Marine_Group_1_thaumarchaeote_sp_SCGC_AAA288_P02/Gen44/' phylogenomic_tree.tree
sed -i 's/Metallosphaera_sedula_DSM_5348/Gen45/' phylogenomic_tree.tree
sed -i 's/Metallosphaera_yellowstonensis_MK1/Gen46/' phylogenomic_tree.tree
sed -i 's/Methanocella_arvoryzae_MRE50/Gen47/' phylogenomic_tree.tree
sed -i 's/Methanocorpusculum_labreanum_Z/Gen48/' phylogenomic_tree.tree
sed -i 's/Methanopyrus_kandleri_AV19/Gen49/' phylogenomic_tree.tree
sed -i 's/Methanosarcina_mazei_Go1/Gen50/' phylogenomic_tree.tree
sed -i 's/Methanothermus_fervidus_DSM_2088/Gen51/' phylogenomic_tree.tree
sed -i 's/Methanotorris_igneus_Kol_5/Gen52/' phylogenomic_tree.tree
sed -i 's/Natrialba_magadii_ATCC_43099/Gen53/' phylogenomic_tree.tree
sed -i 's/Natronomonas_pharaonis_DSM_2160/Gen54/' phylogenomic_tree.tree
sed -i 's/Nitrosarchaeum_koreense_MY1/Gen55/' phylogenomic_tree.tree
sed -i 's/Nitrosarchaeum_limnium_BG20/Gen56/' phylogenomic_tree.tree
sed -i 's/Nitrosarchaeum_limnium_SFB1/Gen57/' phylogenomic_tree.tree
sed -i 's/Nitrosoarchaeum-Baikal-G1-C1/Gen58/' phylogenomic_tree.tree
sed -i 's/Nitrosoarchaeum_sp_BD3/Gen59/' phylogenomic_tree.tree
sed -i 's/Nitrosocosmicus_hydrocola_strain_G61/Gen60/' phylogenomic_tree.tree
sed -i 's/Nitrosocosmicus_oleophilus_strain_MY3/Gen61/' phylogenomic_tree.tree
sed -i 's/Nitrosomarinus_catalina_strain_SPOT01/Gen62/' phylogenomic_tree.tree
sed -i 's/Nitrosopelagicus_brevis_U25/Gen63/' phylogenomic_tree.tree
sed -i 's/Nitrosopelagicus_brevis_strain_CN25/Gen64/' phylogenomic_tree.tree
sed -i 's/Nitrosopelagicus_sp_REDSEA-S31_B2/Gen65/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_1/Gen66/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_2/Gen67/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_3/Gen68/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_iota_1/Gen69/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_1/Gen70/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_2/Gen71/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_3/Gen72/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_4/Gen73/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_5/Gen74/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilus_adriaticus_strain_NF5/Gen75/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilus_koreensis_AR1/Gen76/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilus_maritimus_SCM1/Gen77/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilus_salaria_BD31/Gen78/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilus_sediminis_AR2/Gen79/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilus_sp_D3C/Gen80/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilus_sp_DDS1/Gen81/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilus_sp_Nsub/Gen82/' phylogenomic_tree.tree
sed -i 's/Nitrososphaera_evergladensis_SR1/Gen83/' phylogenomic_tree.tree
sed -i 's/Nitrososphaera_gargensis_Ga9/Gen84/' phylogenomic_tree.tree
sed -i 's/Nitrososphaera_viennensis_EN76/Gen85/' phylogenomic_tree.tree
sed -i 's/Nitrosotalea_bavarica_SbT1/Gen86/' phylogenomic_tree.tree
sed -i 's/Nitrosotalea_devanaterra_Nd1/Gen87/' phylogenomic_tree.tree
sed -i 's/Nitrosotalea_koreensis_CS/Gen88/' phylogenomic_tree.tree
sed -i 's/Nitrosotalea_sinensis_Nd2/Gen89/' phylogenomic_tree.tree
sed -i 's/Nitrosotalea_sp_CS_isolate_NCS1/Gen90/' phylogenomic_tree.tree
sed -i 's/Nitrosotenuis_aquarius_strain_AQ6F/Gen91/' phylogenomic_tree.tree
sed -i 's/Nitrosotenuis_chungbukensis_MY2/Gen92/' phylogenomic_tree.tree
sed -i 's/Nitrosotenuis_cloacae_strain_SAT1/Gen93/' phylogenomic_tree.tree
sed -i 's/Picrophilus_torridus_DSM_9790/Gen94/' phylogenomic_tree.tree
sed -i 's/Pyrobaculum_aerophilum_str_IM2/Gen95/' phylogenomic_tree.tree
sed -i 's/Pyrobaculum_arsenaticum_DSM_13514/Gen96/' phylogenomic_tree.tree
sed -i 's/Pyrobaculum_calidifontis_JCM_11548__crenarchaeotes_2/Gen97/' phylogenomic_tree.tree
sed -i 's/Pyrobaculum_islandicum_DSM_4184/Gen98/' phylogenomic_tree.tree
sed -i 's/Pyrococcus_abyssi_GE5/Gen99/' phylogenomic_tree.tree
sed -i 's/Pyrococcus_furiosus_DSM_3638_2/Gen100/' phylogenomic_tree.tree
sed -i 's/Pyrococcus_horikoshii_OT3__euryarchaeotes_2/Gen101/' phylogenomic_tree.tree
sed -i 's/Pyrococcus_yayanosii_CH1/Gen102/' phylogenomic_tree.tree
sed -i 's/SB_01/Gen103/' phylogenomic_tree.tree
sed -i 's/SB_02/Gen104/' phylogenomic_tree.tree
sed -i 's/SMM_01/Gen105/' phylogenomic_tree.tree
sed -i 's/Saccharolobus_solfataricus_P2/Gen106/' phylogenomic_tree.tree
sed -i 's/Sulfolobus_acidocaldarius_DSM_639/Gen107/' phylogenomic_tree.tree
sed -i 's/Sulfolobus_islandicus_L_D_8_5/Gen108/' phylogenomic_tree.tree
sed -i 's/Sulfolobus_solfataricus_P2/Gen109/' phylogenomic_tree.tree
sed -i 's/Sulfolobus_tokodaii_str_7/Gen110/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_CSP1-1/Gen145/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_N4/Gen112/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_RBG_16_49_8/Gen113/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_SCGC_AAA007-O23/Gen114/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_UBA141/Gen115/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_UBA160/Gen116/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_UBA164/Gen117/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_UBA183/Gen118/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_UBA57/Gen119/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_isolate_MTA5/Gen120/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_strain_BS3/Gen121/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_strain_BS4/Gen122/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_strain_DS1/Gen123/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_bin_Fn1/Gen124/' phylogenomic_tree.tree
sed -i 's/Thermococcus_barophilus_MP/Gen125/' phylogenomic_tree.tree
sed -i 's/Thermococcus_gammatolerans_EJ3/Gen126/' phylogenomic_tree.tree
sed -i 's/Thermococcus_litoralis_DSM_5473/Gen127/' phylogenomic_tree.tree
sed -i 's/Thermofilum_pendens_Hrk_5/Gen128/' phylogenomic_tree.tree
sed -i 's/Thermoplasma_acidophilum_DSM_1728/Gen129/' phylogenomic_tree.tree
sed -i 's/Thermoplasma_volcanium_GSS1/Gen130/' phylogenomic_tree.tree
sed -i 's/Thermoproteus_tenax_Kra_1/Gen131/' phylogenomic_tree.tree
sed -i 's/Unclassified_Aigarchaeota_JZ_bin_40/Gen132/' phylogenomic_tree.tree
sed -i 's/Unclassified_Thaumarchaeota_DRTY_7_bin_36/Gen133/' phylogenomic_tree.tree
sed -i 's/Vulcanisaeta_distributa_DSM_14429/Gen134/' phylogenomic_tree.tree
sed -i 's/XS83_01/Gen135/' phylogenomic_tree.tree
sed -i 's/XS83_02/Gen136/' phylogenomic_tree.tree
sed -i 's/XS84_Bin1/Gen137/' phylogenomic_tree.tree
sed -i 's/XS84_Bin2/Gen138/' phylogenomic_tree.tree
sed -i 's/XS84_Bin3/Gen139/' phylogenomic_tree.tree
sed -i 's/XS87_01/Gen140/' phylogenomic_tree.tree
sed -i 's/XS87_02/Gen141/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_YK1309_1N_NP_iota/Gen142/' phylogenomic_tree.tree
sed -i 's/YK1312_12N_NP_theta/Gen143/' phylogenomic_tree.tree
sed -i 's/Nitrosopumilales_archaeon_isolate_NPMR_NP_iota_1/Gen144/' phylogenomic_tree.tree
sed -i 's/D197_116/Gen147/' phylogenomic_tree.tree
sed -i 's/D197_2/Gen148/' phylogenomic_tree.tree
sed -i 's/Mariana_Trench_sediment_5533m_4-6cm_Bin1/Gen149/' phylogenomic_tree.tree
sed -i 's/Deep-sea_sediment_ERR1730303_Bin1/Gen150/' phylogenomic_tree.tree
sed -i 's/Deep-sea_sediment_DRR121209_Bin1/Gen151/' phylogenomic_tree.tree
sed -i 's/Deep-sea_sediment_DRR121219_Bin1/Gen152/' phylogenomic_tree.tree
sed -i 's/D175_87_reformat/Gen153/' phylogenomic_tree.tree
sed -i 's/D155_102_reformat/Gen154/' phylogenomic_tree.tree
sed -i 's/D125_37_reformat/Gen155/' phylogenomic_tree.tree
sed -i 's/D125_54_reformat/Gen157/' phylogenomic_tree.tree
sed -i 's/D175_134_reformat/Gen156/' phylogenomic_tree.tree
sed -i 's/D185_106_reformat/Gen158/' phylogenomic_tree.tree
sed -i 's/D185_135_reformat/Gen159/' phylogenomic_tree.tree
sed -i 's/D111_44_reformat/Gen160/' phylogenomic_tree.tree
sed -i 's/D111_58_reformat/Gen161/' phylogenomic_tree.tree
sed -i 's/D185_135_reformat/Gen162/' phylogenomic_tree.tree
sed -i 's/D155_85_reformat/Gen163/' phylogenomic_tree.tree
sed -i 's/F/Gen29/' phylogenomic_tree.tree
sed -i 's/HMT_AABW_S15_53/Gen164/' phylogenomic_tree.tree
sed -i 's/HMT_NADW_S23_34/Gen165/' phylogenomic_tree.tree
sed -i 's/HMT_AABW/Gen/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_SP3992/Gen167/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_ASW8/Gen168/' phylogenomic_tree.tree
sed -i 's/HMT_NADW/Gen169/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_ASW2_bin45/Gen170/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_SAT139/Gen171/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_EAC691/Gen172/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_YP1_bin3/Gen173/' phylogenomic_tree.tree
sed -i 's/Thaumarchaeota_archaeon_strain_BS1/Gen174/' phylogenomic_tree.tree
sed -i 's/HMT_ATL/Gen175/' phylogenomic_tree.tree
sed -i 's/HMT_AAIW/Gen176/' phylogenomic_tree.tree
sed -i 's/HMT_PAC/Gen177/' phylogenomic_tree.tree
