sed -i 's/Gen99/Thaumarchaeota_archaeon_UBA183/' FigTree.tre
sed -i 's/Gen98/Thaumarchaeota_archaeon_UBA141/' FigTree.tre
sed -i 's/Gen97/Thaumarchaeota_archaeon_RBG_16_49_8/' FigTree.tre
sed -i 's/Gen96/D197_116/' FigTree.tre
sed -i 's/Gen95/D197_2/' FigTree.tre
sed -i 's/Gen94/Mariana_Trench_sediment_5533m_4-6cm_Bin1/' FigTree.tre
sed -i 's/Gen93/XS84_Bin3/' FigTree.tre
sed -i 's/Gen92/XS84_Bin2/' FigTree.tre
sed -i 's/Gen91/XS84_Bin1/' FigTree.tre
sed -i 's/Gen90/Deep-sea_sediment_ERR1730303_Bin1/' FigTree.tre
sed -i 's/Gen9/Nitrosopumilus_maritimus_SCM1/' FigTree.tre
sed -i 's/Gen89/Deep-sea_sediment_DRR121209_Bin1/' FigTree.tre
sed -i 's/Gen88/Deep-sea_sediment_DRR121219_Bin1/' FigTree.tre
sed -i 's/Gen87/Thaumarchaeota_archaeon_SAT139/' FigTree.tre
sed -i 's/Gen86/Thaumarchaeota_archaeon_EAC691/' FigTree.tre
sed -i 's/Gen85/Thaumarchaeota_ASW2_bin45/' FigTree.tre
sed -i 's/Gen84/Thaumarchaeota_archaeon_SP3992/' FigTree.tre
sed -i 's/Gen83/HMT_AAIW/' FigTree.tre
sed -i 's/Gen82/Thaumarchaeota_ASW8/' FigTree.tre
sed -i 's/Gen81/Thaumarchaeota_archaeon_UBA57/' FigTree.tre
sed -i 's/Gen80/HMT_NADW/' FigTree.tre
sed -i 's/Gen8/Nitrosopumilus_koreensis_AR1/' FigTree.tre
sed -i 's/Gen79/HMT_ATL/' FigTree.tre
sed -i 's/Gen78/HMT_NADW_S23_34/' FigTree.tre
sed -i 's/Gen77/HMT_AABW_S15_53/' FigTree.tre
sed -i 's/Gen76/HMT_PAC/' FigTree.tre
sed -i 's/Gen75/HMT_AABW/' FigTree.tre
sed -i 's/Gen74/Candidatus_Nitrosocaldus_cavascurensis_strain/' FigTree.tre
sed -i 's/Gen73/Candidatus_Nitrosocaldus_islandicus_isolate_3F/' FigTree.tre
sed -i 's/Gen72/Thaumarchaeota_archaeon_isolate_MTA5/' FigTree.tre
sed -i 's/Gen71/Nitrososphaera_gargensis_Ga9/' FigTree.tre
sed -i 's/Gen70/Nitrososphaera_evergladensis_SR1/' FigTree.tre
sed -i 's/Gen7/Nitrosopumilus_sp_D3C/' FigTree.tre
sed -i 's/Gen69/Nitrososphaera_viennensis_EN76/' FigTree.tre
sed -i 's/Gen68/Nitrosocosmicus_oleophilus_strain_MY3/' FigTree.tre
sed -i 's/Gen67/Candidatus_Nitrosocosmicus_franklandus_C13/' FigTree.tre
sed -i 's/Gen66/Nitrosocosmicus_hydrocola_strain_G61/' FigTree.tre
sed -i 's/Gen65/Nitrosotalea_sinensis_Nd2/' FigTree.tre
sed -i 's/Gen64/Nitrosotalea_bavarica_SbT1/' FigTree.tre
sed -i 's/Gen63/Nitrosotalea_devanaterra_Nd1/' FigTree.tre
sed -i 's/Gen62/Nitrosotalea_koreensis_CS/' FigTree.tre
sed -i 's/Gen61/Nitrosopumilales_archaeon_isolate_NPMR_NP_iota_1/' FigTree.tre
sed -i 's/Gen60/Thaumarchaeota_YK1309_1N_NP_iota/' FigTree.tre
sed -i 's/Gen6/Nitrosopumilus_salaria_BD31/' FigTree.tre
sed -i 's/Gen59/Nitrosotenuis_chungbukensis_MY2/' FigTree.tre
sed -i 's/Gen58/Thaumarchaeota_archaeon_N4/' FigTree.tre
sed -i 's/Gen57/Nitrosotenuis_aquarius_strain_AQ6F/' FigTree.tre
sed -i 's/Gen56/Nitrosotenuis_cloacae_strain_SAT1/' FigTree.tre
sed -i 's/Gen55/D175_87_reformat/' FigTree.tre
sed -i 's/Gen54/D155_102_reformat/' FigTree.tre
sed -i 's/Gen53/D125_37_reformat/' FigTree.tre
sed -i 's/Gen52/D175_134_reformat/' FigTree.tre
sed -i 's/Gen51/D125_54_reformat/' FigTree.tre
sed -i 's/Gen50/D185_106_reformat/' FigTree.tre
sed -i 's/Gen5/Nitrosomarinus_catalina_strain_SPOT01/' FigTree.tre
sed -i 's/Gen49/Nitrosopelagicus_brevis_U25/' FigTree.tre
sed -i 's/Gen48/Nitrosopelagicus_brevis_strain_CN25/' FigTree.tre
sed -i 's/Gen47/Candidatus_Nitrosopelagicus_sp_Isolate_GoM/' FigTree.tre
sed -i 's/Gen46/Nitrosopelagicus_sp_REDSEA-S31_B2/' FigTree.tre
sed -i 's/Gen45/Marine_Group_1_thaumarchaeote_sp_SCGC_AAA288_P02/' FigTree.tre
sed -i 's/Gen44/AAA799-O18/' FigTree.tre
sed -i 's/Gen43/AAA288-D22/' FigTree.tre
sed -i 's/Gen42/Marine_Group_1_crenarchaeote_sp_SCGC/' FigTree.tre
sed -i 's/Gen41/AAA007-N19/' FigTree.tre
sed -i 's/Gen40/Thaumarchaeota_archaeon_SCGC_AAA007-O23/' FigTree.tre
sed -i 's/Gen4/Nitrosopumilus_sp_Nsub/' FigTree.tre
sed -i 's/Gen39/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_1/' FigTree.tre
sed -i 's/Gen38/HM82_Bin2/' FigTree.tre
sed -i 's/Gen37/HM82_Bin1/' FigTree.tre
sed -i 's/Gen36/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_2/' FigTree.tre
sed -i 's/Gen35/Nitrosopumilales_archaeon_strain_NPMR_NP_delta_3/' FigTree.tre
sed -i 's/Gen34/Thaumarchaeota_CSP1-1/' FigTree.tre
sed -i 's/Gen33/D111_44_reformat/' FigTree.tre
sed -i 's/Gen32/D185_135_reformat/' FigTree.tre
sed -i 's/Gen31/D155_85_reformat/' FigTree.tre
sed -i 's/Gen30/EGM_Bin1/' FigTree.tre
sed -i 's/Gen3/Candidatus_Nitrosopumilus_sp_MTA1/' FigTree.tre
sed -i 's/Gen29/XS83_02/' FigTree.tre
sed -i 's/Gen28/XS83_01/' FigTree.tre
sed -i 's/Gen27/HM45_Bin1/' FigTree.tre
sed -i 's/Gen26/XS87_02/' FigTree.tre
sed -i 's/Gen25/D111_58_reformat/' FigTree.tre
sed -i 's/Gen24/YK1312_12N_NP_theta/' FigTree.tre
sed -i 's/Gen23/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_3/' FigTree.tre
sed -i 's/Gen22/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_4/' FigTree.tre
sed -i 's/Gen21/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_2/' FigTree.tre
sed -i 's/Gen20/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_1/' FigTree.tre
sed -i 's/Gen2/Nitrosopumilus_adriaticus_strain_NF5/' FigTree.tre
sed -i 's/Gen19/Nitrosopumilales_archaeon_strain_NPMR_NP_theta_5/' FigTree.tre
sed -i 's/Gen18/SB_01/' FigTree.tre
sed -i 's/Gen17/EGM_Bin2/' FigTree.tre
sed -i 's/Gen16/HM81_Bin2/' FigTree.tre
sed -i 's/Gen156/Halorhabdus_utahensis_DSM_12940/' FigTree.tre
sed -i 's/Gen155/Aigarchaeota_archaeon_strain_OS1/' FigTree.tre
sed -i 's/Gen154/Unclassified_Aigarchaeota_JZ_bin_40/' FigTree.tre
sed -i 's/Gen153/Candidatus_Caldiarchaeum_subterraneum/' FigTree.tre
sed -i 's/Gen152/Aigarchaeota_archaeon_NZ13_MG1/' FigTree.tre
sed -i 's/Gen151/Aigarchaeota_archaeon_JGI_0000106_J15/' FigTree.tre
sed -i 's/Gen150/Aigarchaeota_archaeon_JGI_MDM2_JNZ_1_K18/' FigTree.tre
sed -i 's/Gen15/SB_02/' FigTree.tre
sed -i 's/Gen149/Candidatus_Korarchaeum_cryptofilum_OPF8/' FigTree.tre
sed -i 's/Gen148/Thermofilum_pendens_Hrk_5/' FigTree.tre
sed -i 's/Gen147/Vulcanisaeta_distributa_DSM_14429/' FigTree.tre
sed -i 's/Gen146/Caldivirga_maquilingensis_IC_167/' FigTree.tre
sed -i 's/Gen145/Thermoproteus_tenax_Kra_1/' FigTree.tre
sed -i 's/Gen144/Pyrobaculum_calidifontis_JCM_11548__crenarchaeotes_2/' FigTree.tre
sed -i 's/Gen143/Pyrobaculum_islandicum_DSM_4184/' FigTree.tre
sed -i 's/Gen142/Pyrobaculum_aerophilum_str_IM2/' FigTree.tre
sed -i 's/Gen141/Pyrobaculum_arsenaticum_DSM_13514/' FigTree.tre
sed -i 's/Gen140/Sulfolobus_tokodaii_str_7/' FigTree.tre
sed -i 's/Gen14/Nitrosarchaeum_koreense_MY1/' FigTree.tre
sed -i 's/Gen139/Sulfolobus_acidocaldarius_DSM_639/' FigTree.tre
sed -i 's/Gen138/Acidianus_hospitalis_W1/' FigTree.tre
sed -i 's/Gen137/Metallosphaera_sedula_DSM_5348/' FigTree.tre
sed -i 's/Gen136/Metallosphaera_yellowstonensis_MK1/' FigTree.tre
sed -i 's/Gen135/Sulfolobus_islandicus_L_D_8_5/' FigTree.tre
sed -i 's/Gen134/Saccharolobus_solfataricus_P2/' FigTree.tre
sed -i 's/Gen133/Sulfolobus_solfataricus_P2/' FigTree.tre
sed -i 's/Gen132/Thermococcus_gammatolerans_EJ3/' FigTree.tre
sed -i 's/Gen131/Thermococcus_barophilus_MP/' FigTree.tre
sed -i 's/Gen130/Thermococcus_litoralis_DSM_5473/' FigTree.tre
sed -i 's/Gen13/Nitrosarchaeum_limnium_SFB1/' FigTree.tre
sed -i 's/Gen129/Pyrococcus_yayanosii_CH1/' FigTree.tre
sed -i 's/Gen128/Pyrococcus_furiosus_DSM_3638_2/' FigTree.tre
sed -i 's/Gen127/Pyrococcus_abyssi_GE5/' FigTree.tre
sed -i 's/Gen126/Pyrococcus_horikoshii_OT3__euryarchaeotes_2/' FigTree.tre
sed -i 's/Gen125/Methanopyrus_kandleri_AV19/' FigTree.tre
sed -i 's/Gen124/Methanotorris_igneus_Kol_5/' FigTree.tre
sed -i 's/Gen123/Methanothermus_fervidus_DSM_2088/' FigTree.tre
sed -i 's/Gen122/Aciduliprofundum_boonei_T469/' FigTree.tre
sed -i 's/Gen121/Ferroplasma_acidarmanus_fer1/' FigTree.tre
sed -i 's/Gen120/Picrophilus_torridus_DSM_9790/' FigTree.tre
sed -i 's/Gen12/Nitrosarchaeum_limnium_BG20/' FigTree.tre
sed -i 's/Gen119/Thermoplasma_volcanium_GSS1/' FigTree.tre
sed -i 's/Gen118/Thermoplasma_acidophilum_DSM_1728/' FigTree.tre
sed -i 's/Gen117/Archaeoglobus_veneficus_SNP6/' FigTree.tre
sed -i 's/Gen116/Methanocorpusculum_labreanum_Z/' FigTree.tre
sed -i 's/Gen115/Methanosarcina_mazei_Go1/' FigTree.tre
sed -i 's/Gen114/Methanocella_arvoryzae_MRE50/' FigTree.tre
sed -i 's/Gen113/Halorubrum_lacusprofundi_ATCC_49239/' FigTree.tre
sed -i 's/Gen112/Halogeometricum_borinquense_DSM_11551/' FigTree.tre
sed -i 's/Gen111/Haladaptatus_paucihalophilus_DX253/' FigTree.tre
sed -i 's/Gen110/Natrialba_magadii_ATCC_43099/' FigTree.tre
sed -i 's/Gen11/Nitrosoarchaeum-Baikal-G1-C1/' FigTree.tre
sed -i 's/Gen109/Natronomonas_pharaonis_DSM_2160/' FigTree.tre
sed -i 's/Gen108/Unclassified_Thaumarchaeota_DRTY_7_bin_36/' FigTree.tre
sed -i 's/Gen107/Thaumarchaeota_archaeon_UBA164/' FigTree.tre
sed -i 's/Gen106/Thaumarchaeota_archaeon_strain_DS1/' FigTree.tre
sed -i 's/Gen105/Thaumarchaeota_archaeon_UBA160/' FigTree.tre
sed -i 's/Gen104/Thaumarchaeota_archaeon_strain_BS4/' FigTree.tre
sed -i 's/Gen103/Thaumarchaeota_archaeon_strain_BS1/' FigTree.tre
sed -i 's/Gen102/Thaumarchaeota_archaeon_strain_BS3/' FigTree.tre
sed -i 's/Gen101/Thaumarchaeota_YP1_bin3/' FigTree.tre
sed -i 's/Gen100/Thaumarchaeota_bin_Fn1/' FigTree.tre
sed -i 's/Gen10/Nitrosoarchaeum_sp_BD3/' FigTree.tre
sed -i 's/Gen1/Nitrosopumilus_sp_DDS1/' FigTree.tre
