prodigal -i Methanotorris_igneus_Kol_5_renamed.fa -d Methanotorris_igneus_Kol_5_renamed_cds.fa -a Methanotorris_igneus_Kol_5_renamed_AA.faa -p single
prodigal -i Sulfolobus_islandicus_L_D_8_5_renamed.fa -d Sulfolobus_islandicus_L_D_8_5_renamed_cds.fa -a Sulfolobus_islandicus_L_D_8_5_renamed_AA.faa -p single
prodigal -i Nitrosopumilales_archaeon_strain_NPMR_NP_theta_3_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_theta_3_renamed_cds.fa -a Nitrosopumilales_archaeon_strain_NPMR_NP_theta_3_renamed_AA.faa -p single
prodigal -i Halorubrum_lacusprofundi_ATCC_49239_renamed.fa -d Halorubrum_lacusprofundi_ATCC_49239_renamed_cds.fa -a Halorubrum_lacusprofundi_ATCC_49239_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_strain_BS3_renamed.fa -d Thaumarchaeota_archaeon_strain_BS3_renamed_cds.fa -a Thaumarchaeota_archaeon_strain_BS3_renamed_AA.faa -p single
prodigal -i D175_134_reformat_renamed.fa -d D175_134_reformat_renamed_cds.fa -a D175_134_reformat_renamed_AA.faa -p single
prodigal -i Nitrosoarchaeum_sp_BD3_renamed.fa -d Nitrosoarchaeum_sp_BD3_renamed_cds.fa -a Nitrosoarchaeum_sp_BD3_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_UBA141_renamed.fa -d Thaumarchaeota_archaeon_UBA141_renamed_cds.fa -a Thaumarchaeota_archaeon_UBA141_renamed_AA.faa -p single
prodigal -i Thermococcus_barophilus_MP_renamed.fa -d Thermococcus_barophilus_MP_renamed_cds.fa -a Thermococcus_barophilus_MP_renamed_AA.faa -p single
prodigal -i Pyrococcus_abyssi_GE5_renamed.fa -d Pyrococcus_abyssi_GE5_renamed_cds.fa -a Pyrococcus_abyssi_GE5_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_bin_Fn1_renamed.fa -d Thaumarchaeota_bin_Fn1_renamed_cds.fa -a Thaumarchaeota_bin_Fn1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_SCGC_AAA007-O23_renamed.fa -d Thaumarchaeota_archaeon_SCGC_AAA007-O23_renamed_cds.fa -a Thaumarchaeota_archaeon_SCGC_AAA007-O23_renamed_AA.faa -p single
prodigal -i D125_54_reformat_renamed.fa -d D125_54_reformat_renamed_cds.fa -a D125_54_reformat_renamed_AA.faa -p single
prodigal -i Aigarchaeota_archaeon_strain_OS1_renamed.fa -d Aigarchaeota_archaeon_strain_OS1_renamed_cds.fa -a Aigarchaeota_archaeon_strain_OS1_renamed_AA.faa -p single
prodigal -i Nitrosomarinus_catalina_strain_SPOT01_renamed.fa -d Nitrosomarinus_catalina_strain_SPOT01_renamed_cds.fa -a Nitrosomarinus_catalina_strain_SPOT01_renamed_AA.faa -p single
prodigal -i Nitrosotenuis_aquarius_strain_AQ6F_renamed.fa -d Nitrosotenuis_aquarius_strain_AQ6F_renamed_cds.fa -a Nitrosotenuis_aquarius_strain_AQ6F_renamed_AA.faa -p single
prodigal -i Nitrosopelagicus_brevis_strain_CN25_renamed.fa -d Nitrosopelagicus_brevis_strain_CN25_renamed_cds.fa -a Nitrosopelagicus_brevis_strain_CN25_renamed_AA.faa -p single
prodigal -i Halorhabdus_utahensis_DSM_12940_renamed.fa -d Halorhabdus_utahensis_DSM_12940_renamed_cds.fa -a Halorhabdus_utahensis_DSM_12940_renamed_AA.faa -p single
prodigal -i D197_116_renamed.fa -d D197_116_renamed_cds.fa -a D197_116_renamed_AA.faa -p single
prodigal -i HMT_AAIW_renamed.fa -d HMT_AAIW_renamed_cds.fa -a HMT_AAIW_renamed_AA.faa -p single
prodigal -i Deep-sea_sediment_DRR121219_Bin1_renamed.fa -d Deep-sea_sediment_DRR121219_Bin1_renamed_cds.fa -a Deep-sea_sediment_DRR121219_Bin1_renamed_AA.faa -p single
prodigal -i SB_01_renamed.fa -d SB_01_renamed_cds.fa -a SB_01_renamed_AA.faa -p single
prodigal -i HMT_NADW_S23_34_renamed.fa -d HMT_NADW_S23_34_renamed_cds.fa -a HMT_NADW_S23_34_renamed_AA.faa -p single
prodigal -i HMT_AABW_S15_53_renamed.fa -d HMT_AABW_S15_53_renamed_cds.fa -a HMT_AABW_S15_53_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_SP3992_renamed.fa -d Thaumarchaeota_archaeon_SP3992_renamed_cds.fa -a Thaumarchaeota_archaeon_SP3992_renamed_AA.faa -p single
prodigal -i Vulcanisaeta_distributa_DSM_14429_renamed.fa -d Vulcanisaeta_distributa_DSM_14429_renamed_cds.fa -a Vulcanisaeta_distributa_DSM_14429_renamed_AA.faa -p single
prodigal -i Nitrosarchaeum_limnium_BG20_renamed.fa -d Nitrosarchaeum_limnium_BG20_renamed_cds.fa -a Nitrosarchaeum_limnium_BG20_renamed_AA.faa -p single
prodigal -i Aciduliprofundum_boonei_T469_renamed.fa -d Aciduliprofundum_boonei_T469_renamed_cds.fa -a Aciduliprofundum_boonei_T469_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_strain_BS4_renamed.fa -d Thaumarchaeota_archaeon_strain_BS4_renamed_cds.fa -a Thaumarchaeota_archaeon_strain_BS4_renamed_AA.faa -p single
prodigal -i Nitrosopumilus_koreensis_AR1_renamed.fa -d Nitrosopumilus_koreensis_AR1_renamed_cds.fa -a Nitrosopumilus_koreensis_AR1_renamed_AA.faa -p single
prodigal -i Nitrosopumilales_archaeon_strain_NPMR_NP_theta_4_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_theta_4_renamed_cds.fa -a Nitrosopumilales_archaeon_strain_NPMR_NP_theta_4_renamed_AA.faa -p single
prodigal -i Candidatus_Korarchaeum_cryptofilum_OPF8_renamed.fa -d Candidatus_Korarchaeum_cryptofilum_OPF8_renamed_cds.fa -a Candidatus_Korarchaeum_cryptofilum_OPF8_renamed_AA.faa -p single
prodigal -i Sulfolobus_acidocaldarius_DSM_639_renamed.fa -d Sulfolobus_acidocaldarius_DSM_639_renamed_cds.fa -a Sulfolobus_acidocaldarius_DSM_639_renamed_AA.faa -p single
prodigal -i Sulfolobus_tokodaii_str_7_renamed.fa -d Sulfolobus_tokodaii_str_7_renamed_cds.fa -a Sulfolobus_tokodaii_str_7_renamed_AA.faa -p single
prodigal -i Nitrosarchaeum_limnium_SFB1_renamed.fa -d Nitrosarchaeum_limnium_SFB1_renamed_cds.fa -a Nitrosarchaeum_limnium_SFB1_renamed_AA.faa -p single
prodigal -i HMT_NADW_renamed.fa -d HMT_NADW_renamed_cds.fa -a HMT_NADW_renamed_AA.faa -p single
prodigal -i Deep-sea_sediment_DRR121209_Bin1_renamed.fa -d Deep-sea_sediment_DRR121209_Bin1_renamed_cds.fa -a Deep-sea_sediment_DRR121209_Bin1_renamed_AA.faa -p single
prodigal -i Nitrosopumilus_salaria_BD31_renamed.fa -d Nitrosopumilus_salaria_BD31_renamed_cds.fa -a Nitrosopumilus_salaria_BD31_renamed_AA.faa -p single
prodigal -i Nitrosocosmicus_hydrocola_strain_G61_renamed.fa -d Nitrosocosmicus_hydrocola_strain_G61_renamed_cds.fa -a Nitrosocosmicus_hydrocola_strain_G61_renamed_AA.faa -p single
prodigal -i Sulfolobus_solfataricus_P2_renamed.fa -d Sulfolobus_solfataricus_P2_renamed_cds.fa -a Sulfolobus_solfataricus_P2_renamed_AA.faa -p single
prodigal -i Thermoproteus_tenax_Kra_1_renamed.fa -d Thermoproteus_tenax_Kra_1_renamed_cds.fa -a Thermoproteus_tenax_Kra_1_renamed_AA.faa -p single
prodigal -i Thermococcus_litoralis_DSM_5473_renamed.fa -d Thermococcus_litoralis_DSM_5473_renamed_cds.fa -a Thermococcus_litoralis_DSM_5473_renamed_AA.faa -p single
prodigal -i Archaeoglobus_veneficus_SNP6_renamed.fa -d Archaeoglobus_veneficus_SNP6_renamed_cds.fa -a Archaeoglobus_veneficus_SNP6_renamed_AA.faa -p single
prodigal -i Nitrosotalea_devanaterra_Nd1_renamed.fa -d Nitrosotalea_devanaterra_Nd1_renamed_cds.fa -a Nitrosotalea_devanaterra_Nd1_renamed_AA.faa -p single
prodigal -i XS83_02_renamed.fa -d XS83_02_renamed_cds.fa -a XS83_02_renamed_AA.faa -p single
prodigal -i Picrophilus_torridus_DSM_9790_renamed.fa -d Picrophilus_torridus_DSM_9790_renamed_cds.fa -a Picrophilus_torridus_DSM_9790_renamed_AA.faa -p single
prodigal -i D125_37_reformat_renamed.fa -d D125_37_reformat_renamed_cds.fa -a D125_37_reformat_renamed_AA.faa -p single
prodigal -i Nitrosoarchaeum-Baikal-G1-C1_renamed.fa -d Nitrosoarchaeum-Baikal-G1-C1_renamed_cds.fa -a Nitrosoarchaeum-Baikal-G1-C1_renamed_AA.faa -p single
prodigal -i EGM_Bin1_renamed.fa -d EGM_Bin1_renamed_cds.fa -a EGM_Bin1_renamed_AA.faa -p single
prodigal -i XS84_Bin2_renamed.fa -d XS84_Bin2_renamed_cds.fa -a XS84_Bin2_renamed_AA.faa -p single
prodigal -i Aigarchaeota_archaeon_JGI_MDM2_JNZ_1_K18_renamed.fa -d Aigarchaeota_archaeon_JGI_MDM2_JNZ_1_K18_renamed_cds.fa -a Aigarchaeota_archaeon_JGI_MDM2_JNZ_1_K18_renamed_AA.faa -p single
prodigal -i Nitrosopumilales_archaeon_strain_NPMR_NP_theta_1_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_theta_1_renamed_cds.fa -a Nitrosopumilales_archaeon_strain_NPMR_NP_theta_1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_strain_BS1_renamed.fa -d Thaumarchaeota_archaeon_strain_BS1_renamed_cds.fa -a Thaumarchaeota_archaeon_strain_BS1_renamed_AA.faa -p single
prodigal -i Pyrococcus_furiosus_DSM_3638_2_renamed.fa -d Pyrococcus_furiosus_DSM_3638_2_renamed_cds.fa -a Pyrococcus_furiosus_DSM_3638_2_renamed_AA.faa -p single
prodigal -i Thermofilum_pendens_Hrk_5_renamed.fa -d Thermofilum_pendens_Hrk_5_renamed_cds.fa -a Thermofilum_pendens_Hrk_5_renamed_AA.faa -p single
prodigal -i AAA288-D22_renamed.fa -d AAA288-D22_renamed_cds.fa -a AAA288-D22_renamed_AA.faa -p single
prodigal -i Candidatus_Nitrosopelagicus_sp_Isolate_GoM_renamed.fa -d Candidatus_Nitrosopelagicus_sp_Isolate_GoM_renamed_cds.fa -a Candidatus_Nitrosopelagicus_sp_Isolate_GoM_renamed_AA.faa -p single
prodigal -i D111_58_reformat_renamed.fa -d D111_58_reformat_renamed_cds.fa -a D111_58_reformat_renamed_AA.faa -p single
prodigal -i HM45_Bin1_renamed.fa -d HM45_Bin1_renamed_cds.fa -a HM45_Bin1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_UBA164_renamed.fa -d Thaumarchaeota_archaeon_UBA164_renamed_cds.fa -a Thaumarchaeota_archaeon_UBA164_renamed_AA.faa -p single
prodigal -i Nitrososphaera_evergladensis_SR1_renamed.fa -d Nitrososphaera_evergladensis_SR1_renamed_cds.fa -a Nitrososphaera_evergladensis_SR1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_strain_DS1_renamed.fa -d Thaumarchaeota_archaeon_strain_DS1_renamed_cds.fa -a Thaumarchaeota_archaeon_strain_DS1_renamed_AA.faa -p single
prodigal -i HM82_Bin1_renamed.fa -d HM82_Bin1_renamed_cds.fa -a HM82_Bin1_renamed_AA.faa -p single
prodigal -i Nitrosopelagicus_brevis_U25_renamed.fa -d Nitrosopelagicus_brevis_U25_renamed_cds.fa -a Nitrosopelagicus_brevis_U25_renamed_AA.faa -p single
prodigal -i Thermoplasma_volcanium_GSS1_renamed.fa -d Thermoplasma_volcanium_GSS1_renamed_cds.fa -a Thermoplasma_volcanium_GSS1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_isolate_MTA5_renamed.fa -d Thaumarchaeota_archaeon_isolate_MTA5_renamed_cds.fa -a Thaumarchaeota_archaeon_isolate_MTA5_renamed_AA.faa -p single
prodigal -i Methanosarcina_mazei_Go1_renamed.fa -d Methanosarcina_mazei_Go1_renamed_cds.fa -a Methanosarcina_mazei_Go1_renamed_AA.faa -p single
prodigal -i Nitrosopumilales_archaeon_isolate_NPMR_NP_iota_1_renamed.fa -d Nitrosopumilales_archaeon_isolate_NPMR_NP_iota_1_renamed_cds.fa -a Nitrosopumilales_archaeon_isolate_NPMR_NP_iota_1_renamed_AA.faa -p single
prodigal -i Methanopyrus_kandleri_AV19_renamed.fa -d Methanopyrus_kandleri_AV19_renamed_cds.fa -a Methanopyrus_kandleri_AV19_renamed_AA.faa -p single
prodigal -i Pyrobaculum_islandicum_DSM_4184_renamed.fa -d Pyrobaculum_islandicum_DSM_4184_renamed_cds.fa -a Pyrobaculum_islandicum_DSM_4184_renamed_AA.faa -p single
prodigal -i D155_102_reformat_renamed.fa -d D155_102_reformat_renamed_cds.fa -a D155_102_reformat_renamed_AA.faa -p single
prodigal -i Pyrobaculum_calidifontis_JCM_11548__crenarchaeotes_2_renamed.fa -d Pyrobaculum_calidifontis_JCM_11548__crenarchaeotes_2_renamed_cds.fa -a Pyrobaculum_calidifontis_JCM_11548__crenarchaeotes_2_renamed_AA.faa -p single
prodigal -i Natrialba_magadii_ATCC_43099_renamed.fa -d Natrialba_magadii_ATCC_43099_renamed_cds.fa -a Natrialba_magadii_ATCC_43099_renamed_AA.faa -p single
prodigal -i HMT_AABW_renamed.fa -d HMT_AABW_renamed_cds.fa -a HMT_AABW_renamed_AA.faa -p single
prodigal -i Nitrosopumilales_archaeon_strain_NPMR_NP_delta_2_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_delta_2_renamed_cds.fa -a Nitrosopumilales_archaeon_strain_NPMR_NP_delta_2_renamed_AA.faa -p single
prodigal -i Candidatus_Caldiarchaeum_subterraneum_renamed.fa -d Candidatus_Caldiarchaeum_subterraneum_renamed_cds.fa -a Candidatus_Caldiarchaeum_subterraneum_renamed_AA.faa -p single
prodigal -i Aigarchaeota_archaeon_JGI_0000106_J15_renamed.fa -d Aigarchaeota_archaeon_JGI_0000106_J15_renamed_cds.fa -a Aigarchaeota_archaeon_JGI_0000106_J15_renamed_AA.faa -p single
prodigal -i Nitrosotenuis_cloacae_strain_SAT1_renamed.fa -d Nitrosotenuis_cloacae_strain_SAT1_renamed_cds.fa -a Nitrosotenuis_cloacae_strain_SAT1_renamed_AA.faa -p single
prodigal -i D185_106_reformat_renamed.fa -d D185_106_reformat_renamed_cds.fa -a D185_106_reformat_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_N4_renamed.fa -d Thaumarchaeota_archaeon_N4_renamed_cds.fa -a Thaumarchaeota_archaeon_N4_renamed_AA.faa -p single
prodigal -i Nitrosotalea_koreensis_CS_renamed.fa -d Nitrosotalea_koreensis_CS_renamed_cds.fa -a Nitrosotalea_koreensis_CS_renamed_AA.faa -p single
prodigal -i Marine_Group_1_crenarchaeote_sp_SCGC_renamed.fa -d Marine_Group_1_crenarchaeote_sp_SCGC_renamed_cds.fa -a Marine_Group_1_crenarchaeote_sp_SCGC_renamed_AA.faa -p single
prodigal -i Caldivirga_maquilingensis_IC_167_renamed.fa -d Caldivirga_maquilingensis_IC_167_renamed_cds.fa -a Caldivirga_maquilingensis_IC_167_renamed_AA.faa -p single
prodigal -i SB_02_renamed.fa -d SB_02_renamed_cds.fa -a SB_02_renamed_AA.faa -p single
prodigal -i Pyrobaculum_aerophilum_str_IM2_renamed.fa -d Pyrobaculum_aerophilum_str_IM2_renamed_cds.fa -a Pyrobaculum_aerophilum_str_IM2_renamed_AA.faa -p single
prodigal -i Unclassified_Thaumarchaeota_DRTY_7_bin_36_renamed.fa -d Unclassified_Thaumarchaeota_DRTY_7_bin_36_renamed_cds.fa -a Unclassified_Thaumarchaeota_DRTY_7_bin_36_renamed_AA.faa -p single
prodigal -i Nitrosopumilales_archaeon_strain_NPMR_NP_delta_3_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_delta_3_renamed_cds.fa -a Nitrosopumilales_archaeon_strain_NPMR_NP_delta_3_renamed_AA.faa -p single
prodigal -i Nitrosopumilus_sp_DDS1_renamed.fa -d Nitrosopumilus_sp_DDS1_renamed_cds.fa -a Nitrosopumilus_sp_DDS1_renamed_AA.faa -p single
prodigal -i Haladaptatus_paucihalophilus_DX253_renamed.fa -d Haladaptatus_paucihalophilus_DX253_renamed_cds.fa -a Haladaptatus_paucihalophilus_DX253_renamed_AA.faa -p single
prodigal -i Mariana_Trench_sediment_5533m_4-6cm_Bin1_renamed.fa -d Mariana_Trench_sediment_5533m_4-6cm_Bin1_renamed_cds.fa -a Mariana_Trench_sediment_5533m_4-6cm_Bin1_renamed_AA.faa -p single
prodigal -i Natronomonas_pharaonis_DSM_2160_renamed.fa -d Natronomonas_pharaonis_DSM_2160_renamed_cds.fa -a Natronomonas_pharaonis_DSM_2160_renamed_AA.faa -p single
prodigal -i Candidatus_Nitrosocaldus_cavascurensis_strain_renamed.fa -d Candidatus_Nitrosocaldus_cavascurensis_strain_renamed_cds.fa -a Candidatus_Nitrosocaldus_cavascurensis_strain_renamed_AA.faa -p single
prodigal -i Marine_Group_1_thaumarchaeote_sp_SCGC_AAA288_P02_renamed.fa -d Marine_Group_1_thaumarchaeote_sp_SCGC_AAA288_P02_renamed_cds.fa -a Marine_Group_1_thaumarchaeote_sp_SCGC_AAA288_P02_renamed_AA.faa -p single
prodigal -i AAA799-O18_renamed.fa -d AAA799-O18_renamed_cds.fa -a AAA799-O18_renamed_AA.faa -p single
prodigal -i XS87_02_renamed.fa -d XS87_02_renamed_cds.fa -a XS87_02_renamed_AA.faa -p single
prodigal -i XS84_Bin3_renamed.fa -d XS84_Bin3_renamed_cds.fa -a XS84_Bin3_renamed_AA.faa -p single
prodigal -i Acidianus_hospitalis_W1_renamed.fa -d Acidianus_hospitalis_W1_renamed_cds.fa -a Acidianus_hospitalis_W1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_EAC691_renamed.fa -d Thaumarchaeota_archaeon_EAC691_renamed_cds.fa -a Thaumarchaeota_archaeon_EAC691_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_UBA57_renamed.fa -d Thaumarchaeota_archaeon_UBA57_renamed_cds.fa -a Thaumarchaeota_archaeon_UBA57_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_UBA183_renamed.fa -d Thaumarchaeota_archaeon_UBA183_renamed_cds.fa -a Thaumarchaeota_archaeon_UBA183_renamed_AA.faa -p single
prodigal -i HM81_Bin2_renamed.fa -d HM81_Bin2_renamed_cds.fa -a HM81_Bin2_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_RBG_16_49_8_renamed.fa -d Thaumarchaeota_archaeon_RBG_16_49_8_renamed_cds.fa -a Thaumarchaeota_archaeon_RBG_16_49_8_renamed_AA.faa -p single
prodigal -i HMT_ATL_renamed.fa -d HMT_ATL_renamed_cds.fa -a HMT_ATL_renamed_AA.faa -p single
prodigal -i Metallosphaera_yellowstonensis_MK1_renamed.fa -d Metallosphaera_yellowstonensis_MK1_renamed_cds.fa -a Metallosphaera_yellowstonensis_MK1_renamed_AA.faa -p single
prodigal -i Halogeometricum_borinquense_DSM_11551_renamed.fa -d Halogeometricum_borinquense_DSM_11551_renamed_cds.fa -a Halogeometricum_borinquense_DSM_11551_renamed_AA.faa -p single
prodigal -i Deep-sea_sediment_ERR1730303_Bin1_renamed.fa -d Deep-sea_sediment_ERR1730303_Bin1_renamed_cds.fa -a Deep-sea_sediment_ERR1730303_Bin1_renamed_AA.faa -p single
prodigal -i Pyrococcus_horikoshii_OT3__euryarchaeotes_2_renamed.fa -d Pyrococcus_horikoshii_OT3__euryarchaeotes_2_renamed_cds.fa -a Pyrococcus_horikoshii_OT3__euryarchaeotes_2_renamed_AA.faa -p single
prodigal -i Metallosphaera_sedula_DSM_5348_renamed.fa -d Metallosphaera_sedula_DSM_5348_renamed_cds.fa -a Metallosphaera_sedula_DSM_5348_renamed_AA.faa -p single
prodigal -i HMT_PAC_renamed.fa -d HMT_PAC_renamed_cds.fa -a HMT_PAC_renamed_AA.faa -p single
prodigal -i Nitrosocosmicus_oleophilus_strain_MY3_renamed.fa -d Nitrosocosmicus_oleophilus_strain_MY3_renamed_cds.fa -a Nitrosocosmicus_oleophilus_strain_MY3_renamed_AA.faa -p single
prodigal -i Saccharolobus_solfataricus_P2_renamed.fa -d Saccharolobus_solfataricus_P2_renamed_cds.fa -a Saccharolobus_solfataricus_P2_renamed_AA.faa -p single
prodigal -i Pyrobaculum_arsenaticum_DSM_13514_renamed.fa -d Pyrobaculum_arsenaticum_DSM_13514_renamed_cds.fa -a Pyrobaculum_arsenaticum_DSM_13514_renamed_AA.faa -p single
prodigal -i HM82_Bin2_renamed.fa -d HM82_Bin2_renamed_cds.fa -a HM82_Bin2_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_YP1_bin3_renamed.fa -d Thaumarchaeota_YP1_bin3_renamed_cds.fa -a Thaumarchaeota_YP1_bin3_renamed_AA.faa -p single
prodigal -i Nitrosotalea_bavarica_SbT1_renamed.fa -d Nitrosotalea_bavarica_SbT1_renamed_cds.fa -a Nitrosotalea_bavarica_SbT1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_CSP1-1_renamed.fa -d Thaumarchaeota_CSP1-1_renamed_cds.fa -a Thaumarchaeota_CSP1-1_renamed_AA.faa -p single
prodigal -i Nitrososphaera_viennensis_EN76_renamed.fa -d Nitrososphaera_viennensis_EN76_renamed_cds.fa -a Nitrososphaera_viennensis_EN76_renamed_AA.faa -p single
prodigal -i Aigarchaeota_archaeon_NZ13_MG1_renamed.fa -d Aigarchaeota_archaeon_NZ13_MG1_renamed_cds.fa -a Aigarchaeota_archaeon_NZ13_MG1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_UBA160_renamed.fa -d Thaumarchaeota_archaeon_UBA160_renamed_cds.fa -a Thaumarchaeota_archaeon_UBA160_renamed_AA.faa -p single
prodigal -i D197_2_renamed.fa -d D197_2_renamed_cds.fa -a D197_2_renamed_AA.faa -p single
prodigal -i Candidatus_Nitrosocaldus_islandicus_isolate_3F_renamed.fa -d Candidatus_Nitrosocaldus_islandicus_isolate_3F_renamed_cds.fa -a Candidatus_Nitrosocaldus_islandicus_isolate_3F_renamed_AA.faa -p single
prodigal -i Nitrosopumilus_sp_Nsub_renamed.fa -d Nitrosopumilus_sp_Nsub_renamed_cds.fa -a Nitrosopumilus_sp_Nsub_renamed_AA.faa -p single
prodigal -i Pyrococcus_yayanosii_CH1_renamed.fa -d Pyrococcus_yayanosii_CH1_renamed_cds.fa -a Pyrococcus_yayanosii_CH1_renamed_AA.faa -p single
prodigal -i AAA007-N19_renamed.fa -d AAA007-N19_renamed_cds.fa -a AAA007-N19_renamed_AA.faa -p single
prodigal -i YK1312_12N_NP_theta_renamed.fa -d YK1312_12N_NP_theta_renamed_cds.fa -a YK1312_12N_NP_theta_renamed_AA.faa -p single
prodigal -i Nitrosopumilus_maritimus_SCM1_renamed.fa -d Nitrosopumilus_maritimus_SCM1_renamed_cds.fa -a Nitrosopumilus_maritimus_SCM1_renamed_AA.faa -p single
prodigal -i Nitrososphaera_gargensis_Ga9_renamed.fa -d Nitrososphaera_gargensis_Ga9_renamed_cds.fa -a Nitrososphaera_gargensis_Ga9_renamed_AA.faa -p single
prodigal -i D155_85_reformat_renamed.fa -d D155_85_reformat_renamed_cds.fa -a D155_85_reformat_renamed_AA.faa -p single
prodigal -i Nitrosopumilales_archaeon_strain_NPMR_NP_theta_5_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_theta_5_renamed_cds.fa -a Nitrosopumilales_archaeon_strain_NPMR_NP_theta_5_renamed_AA.faa -p single
prodigal -i Nitrosopumilales_archaeon_strain_NPMR_NP_delta_1_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_delta_1_renamed_cds.fa -a Nitrosopumilales_archaeon_strain_NPMR_NP_delta_1_renamed_AA.faa -p single
prodigal -i Candidatus_Nitrosocosmicus_franklandus_C13_renamed.fa -d Candidatus_Nitrosocosmicus_franklandus_C13_renamed_cds.fa -a Candidatus_Nitrosocosmicus_franklandus_C13_renamed_AA.faa -p single
prodigal -i Thermococcus_gammatolerans_EJ3_renamed.fa -d Thermococcus_gammatolerans_EJ3_renamed_cds.fa -a Thermococcus_gammatolerans_EJ3_renamed_AA.faa -p single
prodigal -i Methanocorpusculum_labreanum_Z_renamed.fa -d Methanocorpusculum_labreanum_Z_renamed_cds.fa -a Methanocorpusculum_labreanum_Z_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_ASW2_bin45_renamed.fa -d Thaumarchaeota_ASW2_bin45_renamed_cds.fa -a Thaumarchaeota_ASW2_bin45_renamed_AA.faa -p single
prodigal -i XS83_01_renamed.fa -d XS83_01_renamed_cds.fa -a XS83_01_renamed_AA.faa -p single
prodigal -i Nitrosopelagicus_sp_REDSEA-S31_B2_renamed.fa -d Nitrosopelagicus_sp_REDSEA-S31_B2_renamed_cds.fa -a Nitrosopelagicus_sp_REDSEA-S31_B2_renamed_AA.faa -p single
prodigal -i Unclassified_Aigarchaeota_JZ_bin_40_renamed.fa -d Unclassified_Aigarchaeota_JZ_bin_40_renamed_cds.fa -a Unclassified_Aigarchaeota_JZ_bin_40_renamed_AA.faa -p single
prodigal -i Nitrosopumilales_archaeon_strain_NPMR_NP_theta_2_renamed.fa -d Nitrosopumilales_archaeon_strain_NPMR_NP_theta_2_renamed_cds.fa -a Nitrosopumilales_archaeon_strain_NPMR_NP_theta_2_renamed_AA.faa -p single
prodigal -i Methanothermus_fervidus_DSM_2088_renamed.fa -d Methanothermus_fervidus_DSM_2088_renamed_cds.fa -a Methanothermus_fervidus_DSM_2088_renamed_AA.faa -p single
prodigal -i Candidatus_Nitrosopumilus_sp_MTA1_renamed.fa -d Candidatus_Nitrosopumilus_sp_MTA1_renamed_cds.fa -a Candidatus_Nitrosopumilus_sp_MTA1_renamed_AA.faa -p single
prodigal -i XS84_Bin1_renamed.fa -d XS84_Bin1_renamed_cds.fa -a XS84_Bin1_renamed_AA.faa -p single
prodigal -i D111_44_reformat_renamed.fa -d D111_44_reformat_renamed_cds.fa -a D111_44_reformat_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_ASW8_renamed.fa -d Thaumarchaeota_ASW8_renamed_cds.fa -a Thaumarchaeota_ASW8_renamed_AA.faa -p single
prodigal -i Methanocella_arvoryzae_MRE50_renamed.fa -d Methanocella_arvoryzae_MRE50_renamed_cds.fa -a Methanocella_arvoryzae_MRE50_renamed_AA.faa -p single
prodigal -i EGM_Bin2_renamed.fa -d EGM_Bin2_renamed_cds.fa -a EGM_Bin2_renamed_AA.faa -p single
prodigal -i Nitrosotalea_sinensis_Nd2_renamed.fa -d Nitrosotalea_sinensis_Nd2_renamed_cds.fa -a Nitrosotalea_sinensis_Nd2_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_SAT139_renamed.fa -d Thaumarchaeota_archaeon_SAT139_renamed_cds.fa -a Thaumarchaeota_archaeon_SAT139_renamed_AA.faa -p single
prodigal -i D185_135_reformat_renamed.fa -d D185_135_reformat_renamed_cds.fa -a D185_135_reformat_renamed_AA.faa -p single
prodigal -i Thermoplasma_acidophilum_DSM_1728_renamed.fa -d Thermoplasma_acidophilum_DSM_1728_renamed_cds.fa -a Thermoplasma_acidophilum_DSM_1728_renamed_AA.faa -p single
prodigal -i Nitrosopumilus_adriaticus_strain_NF5_renamed.fa -d Nitrosopumilus_adriaticus_strain_NF5_renamed_cds.fa -a Nitrosopumilus_adriaticus_strain_NF5_renamed_AA.faa -p single
prodigal -i Nitrosotenuis_chungbukensis_MY2_renamed.fa -d Nitrosotenuis_chungbukensis_MY2_renamed_cds.fa -a Nitrosotenuis_chungbukensis_MY2_renamed_AA.faa -p single
prodigal -i Ferroplasma_acidarmanus_fer1_renamed.fa -d Ferroplasma_acidarmanus_fer1_renamed_cds.fa -a Ferroplasma_acidarmanus_fer1_renamed_AA.faa -p single
prodigal -i Nitrosopumilus_sp_D3C_renamed.fa -d Nitrosopumilus_sp_D3C_renamed_cds.fa -a Nitrosopumilus_sp_D3C_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_YK1309_1N_NP_iota_renamed.fa -d Thaumarchaeota_YK1309_1N_NP_iota_renamed_cds.fa -a Thaumarchaeota_YK1309_1N_NP_iota_renamed_AA.faa -p single
prodigal -i D175_87_reformat_renamed.fa -d D175_87_reformat_renamed_cds.fa -a D175_87_reformat_renamed_AA.faa -p single
prodigal -i Nitrosarchaeum_koreense_MY1_renamed.fa -d Nitrosarchaeum_koreense_MY1_renamed_cds.fa -a Nitrosarchaeum_koreense_MY1_renamed_AA.faa -p single
