prodigal -i Deep-sea_sediment_ERR1730303_Bin1_renamed.fa -d Deep-sea_sediment_ERR1730303_Bin1_renamed_cds.fa -a Deep-sea_sediment_ERR1730303_Bin1_renamed_AA.faa -p single
prodigal -i D197_2_renamed.fa -d D197_2_renamed_cds.fa -a D197_2_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_strain_BS3_renamed.fa -d Thaumarchaeota_archaeon_strain_BS3_renamed_cds.fa -a Thaumarchaeota_archaeon_strain_BS3_renamed_AA.faa -p single
prodigal -i XS84_Bin2_renamed.fa -d XS84_Bin2_renamed_cds.fa -a XS84_Bin2_renamed_AA.faa -p single
prodigal -i HMT_AABW_renamed.fa -d HMT_AABW_renamed_cds.fa -a HMT_AABW_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_RBG_16_49_8_renamed.fa -d Thaumarchaeota_archaeon_RBG_16_49_8_renamed_cds.fa -a Thaumarchaeota_archaeon_RBG_16_49_8_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_UBA183_renamed.fa -d Thaumarchaeota_archaeon_UBA183_renamed_cds.fa -a Thaumarchaeota_archaeon_UBA183_renamed_AA.faa -p single
prodigal -i Mariana_Trench_sediment_5533m_4-6cm_Bin1_renamed.fa -d Mariana_Trench_sediment_5533m_4-6cm_Bin1_renamed_cds.fa -a Mariana_Trench_sediment_5533m_4-6cm_Bin1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_strain_BS4_renamed.fa -d Thaumarchaeota_archaeon_strain_BS4_renamed_cds.fa -a Thaumarchaeota_archaeon_strain_BS4_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_EAC691_renamed.fa -d Thaumarchaeota_archaeon_EAC691_renamed_cds.fa -a Thaumarchaeota_archaeon_EAC691_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_strain_BS1_renamed.fa -d Thaumarchaeota_archaeon_strain_BS1_renamed_cds.fa -a Thaumarchaeota_archaeon_strain_BS1_renamed_AA.faa -p single
prodigal -i HMT_AAIW_renamed.fa -d HMT_AAIW_renamed_cds.fa -a HMT_AAIW_renamed_AA.faa -p single
prodigal -i D197_116_renamed.fa -d D197_116_renamed_cds.fa -a D197_116_renamed_AA.faa -p single
prodigal -i HMT_NADW_renamed.fa -d HMT_NADW_renamed_cds.fa -a HMT_NADW_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_UBA160_renamed.fa -d Thaumarchaeota_archaeon_UBA160_renamed_cds.fa -a Thaumarchaeota_archaeon_UBA160_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_strain_DS1_renamed.fa -d Thaumarchaeota_archaeon_strain_DS1_renamed_cds.fa -a Thaumarchaeota_archaeon_strain_DS1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_SAT139_renamed.fa -d Thaumarchaeota_archaeon_SAT139_renamed_cds.fa -a Thaumarchaeota_archaeon_SAT139_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_UBA141_renamed.fa -d Thaumarchaeota_archaeon_UBA141_renamed_cds.fa -a Thaumarchaeota_archaeon_UBA141_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_bin_Fn1_renamed.fa -d Thaumarchaeota_bin_Fn1_renamed_cds.fa -a Thaumarchaeota_bin_Fn1_renamed_AA.faa -p single
prodigal -i HMT_AABW_S15_53_renamed.fa -d HMT_AABW_S15_53_renamed_cds.fa -a HMT_AABW_S15_53_renamed_AA.faa -p single
prodigal -i HMT_NADW_S23_34_renamed.fa -d HMT_NADW_S23_34_renamed_cds.fa -a HMT_NADW_S23_34_renamed_AA.faa -p single
prodigal -i XS84_Bin1_renamed.fa -d XS84_Bin1_renamed_cds.fa -a XS84_Bin1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_SP3992_renamed.fa -d Thaumarchaeota_archaeon_SP3992_renamed_cds.fa -a Thaumarchaeota_archaeon_SP3992_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_YP1_bin3_renamed.fa -d Thaumarchaeota_YP1_bin3_renamed_cds.fa -a Thaumarchaeota_YP1_bin3_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_UBA57_renamed.fa -d Thaumarchaeota_archaeon_UBA57_renamed_cds.fa -a Thaumarchaeota_archaeon_UBA57_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_ASW2_bin45_renamed.fa -d Thaumarchaeota_ASW2_bin45_renamed_cds.fa -a Thaumarchaeota_ASW2_bin45_renamed_AA.faa -p single
prodigal -i HMT_PAC_renamed.fa -d HMT_PAC_renamed_cds.fa -a HMT_PAC_renamed_AA.faa -p single
prodigal -i HMT_ATL_renamed.fa -d HMT_ATL_renamed_cds.fa -a HMT_ATL_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_archaeon_UBA164_renamed.fa -d Thaumarchaeota_archaeon_UBA164_renamed_cds.fa -a Thaumarchaeota_archaeon_UBA164_renamed_AA.faa -p single
prodigal -i Unclassified_Thaumarchaeota_DRTY_7_bin_36_renamed.fa -d Unclassified_Thaumarchaeota_DRTY_7_bin_36_renamed_cds.fa -a Unclassified_Thaumarchaeota_DRTY_7_bin_36_renamed_AA.faa -p single
prodigal -i Deep-sea_sediment_DRR121219_Bin1_renamed.fa -d Deep-sea_sediment_DRR121219_Bin1_renamed_cds.fa -a Deep-sea_sediment_DRR121219_Bin1_renamed_AA.faa -p single
prodigal -i Deep-sea_sediment_DRR121209_Bin1_renamed.fa -d Deep-sea_sediment_DRR121209_Bin1_renamed_cds.fa -a Deep-sea_sediment_DRR121209_Bin1_renamed_AA.faa -p single
prodigal -i Thaumarchaeota_ASW8_renamed.fa -d Thaumarchaeota_ASW8_renamed_cds.fa -a Thaumarchaeota_ASW8_renamed_AA.faa -p single
prodigal -i XS84_Bin3_renamed.fa -d XS84_Bin3_renamed_cds.fa -a XS84_Bin3_renamed_AA.faa -p single
